# Railway Deployment Template

start = "npm start"

[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
